<a href="https://colab.research.google.com/github/turgonboyev/Google_Colab_uchun/blob/main/Qayta%20indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Qayta indekslash
import pandas as pd
from pandas import Series
import numpy as np

In [6]:
data = {
        'Yil': [2010, 2016, 2020, 2021],
        'Aholi ' : [22, 33, 202, 221],
        'Temp' : [1.5, 2, 3, 5]
}
df = pd.DataFrame(data)
df

    Yil  Aholi   Temp
0  2010      22   1.5
1  2016      33   2.0
2  2020     202   3.0
3  2021     221   5.0

In [8]:
df.index = [10, 16, 20, 21]

In [9]:
df

     Yil  Aholi   Temp
10  2010      22   1.5
16  2016      33   2.0
20  2020     202   3.0
21  2021     221   5.0

In [10]:
ind = [10, 20, 30, 40]
df.reindex(ind)

       Yil  Aholi   Temp
10  2010.0    22.0   1.5
20  2020.0   202.0   3.0
30     NaN     NaN   NaN
40     NaN     NaN   NaN

In [12]:
df.reindex(index=range(10, 20), method='nearest')

     Yil  Aholi   Temp
10  2010      22   1.5
11  2010      22   1.5
12  2010      22   1.5
13  2016      33   2.0
14  2016      33   2.0
15  2016      33   2.0
16  2016      33   2.0
17  2016      33   2.0
18  2020     202   3.0
19  2020     202   3.0

In [13]:
df.reindex(index=range(10, 20), method='ffill')

     Yil  Aholi   Temp
10  2010      22   1.5
11  2010      22   1.5
12  2010      22   1.5
13  2010      22   1.5
14  2010      22   1.5
15  2010      22   1.5
16  2016      33   2.0
17  2016      33   2.0
18  2016      33   2.0
19  2016      33   2.0

In [16]:
df.reindex(columns=['Temp', 'Yil', 'Aholi '])

    Temp   Yil  Aholi
10   1.5  2010      22
16   2.0  2016      33
20   3.0  2020     202
21   5.0  2021     221

In [17]:
df.sample()

     Yil  Aholi   Temp
16  2016      33   2.0

In [19]:
df.sample(3)

     Yil  Aholi   Temp
21  2021     221   5.0
16  2016      33   2.0
10  2010      22   1.5

In [20]:
df.loc[[21,16], ['Aholi ', 'Temp', 'Yil']]

    Aholi   Temp   Yil
21     221   5.0  2021
16      33   2.0  2016

In [ ]:
#Qayta indekslash